// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1nXP2WLAO6UcHgMQD6_AUbA14LbwqfFE',
    appId: '1:853608420626:web:0dc8b1e2f378d8a6d28fcb',
    messagingSenderId: '853608420626',
    projectId: 'todoapp-ac8b7',
    authDomain: 'todoapp-ac8b7.firebaseapp.com',
    storageBucket: 'todoapp-ac8b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVHghjhVzyWWJHyvcvQwe3yImnF4ISi4',
    appId: '1:853608420626:android:0c3692bf90d43ef6d28fcb',
    messagingSenderId: '853608420626',
    projectId: 'todoapp-ac8b7',
    storageBucket: 'todoapp-ac8b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe-IT3zE03LW0N3ghPSPbGQx5WkMNNnJA',
    appId: '1:853608420626:ios:458423adb12a912cd28fcb',
    messagingSenderId: '853608420626',
    projectId: 'todoapp-ac8b7',
    storageBucket: 'todoapp-ac8b7.firebasestorage.app',
    iosBundleId: 'com.example.menu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe-IT3zE03LW0N3ghPSPbGQx5WkMNNnJA',
    appId: '1:853608420626:ios:458423adb12a912cd28fcb',
    messagingSenderId: '853608420626',
    projectId: 'todoapp-ac8b7',
    storageBucket: 'todoapp-ac8b7.firebasestorage.app',
    iosBundleId: 'com.example.menu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1nXP2WLAO6UcHgMQD6_AUbA14LbwqfFE',
    appId: '1:853608420626:web:ff6206b4859df364d28fcb',
    messagingSenderId: '853608420626',
    projectId: 'todoapp-ac8b7',
    authDomain: 'todoapp-ac8b7.firebaseapp.com',
    storageBucket: 'todoapp-ac8b7.firebasestorage.app',
  );
}
